package com.jdmedia.controller;
import com.jdmedia.model.*;
import com.jdmedia.service.AppContext;
import javafx.concurrent.Task;
import javafx.fxml.FXML;
import javafx.scene.control.*;
import java.nio.file.*;
import java.util.*;
public final class AnalysisController {
 private static Path folder; private static List<Path> selectedFiles; private static List<MediaFile> media=List.of(); private final Map<Path,Integer> audioChoices=new HashMap<>(); private final AppContext context; @FXML private Label folderLabel;@FXML private ListView<MediaFile> filesList;@FXML private ComboBox<StreamInfo> audioBox;@FXML private CheckBox applyAudio,hdrToSdr;@FXML private ComboBox<String> subtitlesBox;@FXML private Button continueButton;
 public AnalysisController(AppContext context){this.context=context;}public static void setFolder(Path value){folder=value;}public static void setFiles(List<Path> value){selectedFiles=value;}public static List<MediaFile> media(){return media;}
 @FXML public void initialize(){folderLabel.setText(selectedFiles==null?folder.toString():selectedFiles.getFirst().toString());applyAudio.setSelected(true);filesList.setCellFactory(v->new ListCell<>(){protected void updateItem(MediaFile item,boolean empty){super.updateItem(item,empty);setText(empty?null:item.fileName()+"  •  "+item.resolution()+"  •  "+item.videoCodec());}});filesList.getSelectionModel().selectedItemProperty().addListener((o,a,b)->showStreams(b));audioBox.valueProperty().addListener((o,a,b)->{MediaFile selected=filesList.getSelectionModel().getSelectedItem();if(selected!=null&&b!=null)audioChoices.put(selected.path(),b.index());});scan();}
 private void scan(){Task<List<MediaFile>> task=new Task<>(){protected List<MediaFile> call()throws Exception{List<Path> paths=selectedFiles==null?context.analysis().findVideos(folder):selectedFiles;List<MediaFile> found=new ArrayList<>();int i=0;for(Path p:paths){updateMessage("Analizando "+p.getFileName());found.add(context.analysis().inspect(p));updateProgress(++i,paths.size());}return found;}};task.setOnSucceeded(e->{media=task.getValue();filesList.getItems().setAll(media);continueButton.setDisable(media.isEmpty());context.status().info(media.size()+" vídeo(s) analizados.");if(!media.isEmpty())filesList.getSelectionModel().selectFirst();});task.setOnFailed(e->context.status().error(task.getException().getMessage()));context.status().progress("Buscando vídeos…",-1);new Thread(task,"media-analysis").start();}
 private void showStreams(MediaFile file){audioBox.getItems().clear();if(file==null)return;audioBox.getItems().addAll(file.audioStreams());subtitlesBox.getItems().setAll("Mantener subtítulos compatibles con MP4","Eliminar subtítulos");subtitlesBox.getSelectionModel().selectFirst();Integer choice=audioChoices.get(file.path());if(choice!=null)file.audioStreams().stream().filter(s->s.index()==choice).findFirst().ifPresent(audioBox::setValue);}
 @FXML private void continueFlow(){StreamInfo audio=audioBox.getValue();if(audio==null){context.status().error("Selecciona explícitamente una pista de audio.");return;}if(applyAudio.isSelected())for(MediaFile file:media)audioChoices.put(file.path(),audio.index());if(audioChoices.size()!=media.size()){context.status().error("Selecciona una pista para cada vídeo o activa aplicar al resto.");return;}ConversionOptions.SubtitleMode subtitles="Eliminar subtítulos".equals(subtitlesBox.getValue())?ConversionOptions.SubtitleMode.REMOVE:ConversionOptions.SubtitleMode.KEEP;SummaryController.setOptions(new ConversionOptions("medium",22,Map.copyOf(audioChoices),subtitles,false,hdrToSdr.isSelected()));context.navigation().show("summary-view.fxml");}
 @FXML private void back(){context.navigation().show("folder-view.fxml");}
}
